version: "3.8"
services:
  appserver:
    build: .
    container_name: appserver
    hostname: 'appserver'
    command: bash -c "
      ./docker.sh"
    ports:
    - 8000:8000
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - dbserver

  dbserver:
    image: library/postgres:latest
    container_name: tinyurl_db
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: P4ssw0Rd!
      POSTGRES_USER: urlshortuser
      POSTGRES_DB: urlshortdb
    ports:
      - 5432:5432
volumes:
  postgres_data:
