# Generated by Django 3.2.3 on 2021-05-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0002_auto_20210515_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('clientIp', models.CharField(max_length=255)),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_track', to='urlapi.urls')),
            ],
            options={
                'verbose_name': 'Url Track',
                'verbose_name_plural': 'Url Tracks',
            },
        ),
    ]
