# Generated by Django 3.2.3 on 2021-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0003_urlstrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstrack',
            name='clientIp',
            field=models.CharField(default='127.0.0.1', max_length=255),
        ),
    ]
