# Generated by Django 3.2.3 on 2021-05-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0004_alter_urlstrack_clientip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlsTrack',
            new_name='UrlLog',
        ),
        migrations.AlterModelOptions(
            name='urllog',
            options={'verbose_name': 'Url Log', 'verbose_name_plural': 'Url Log'},
        ),
    ]
