# Generated by Django 3.2.3 on 2021-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0005_auto_20210515_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessCount', models.IntegerField(default=0)),
                ('redirectCount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Url Log',
                'verbose_name_plural': 'Url Log',
            },
        ),
        migrations.RemoveField(
            model_name='urls',
            name='count',
        ),
        migrations.DeleteModel(
            name='UrlLog',
        ),
        migrations.AddField(
            model_name='urlstat',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_track', to='urlapi.urls'),
        ),
    ]
