# Generated by Django 3.2.3 on 2021-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0006_auto_20210515_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='shortCode',
            field=models.CharField(default=0, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
