# Generated by Django 3.2.3 on 2021-05-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0007_urls_shortcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlstat',
            options={},
        ),
    ]
