# Generated by Django 3.2.3 on 2021-05-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0008_alter_urlstat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlstat',
            options={'verbose_name': 'Url Log', 'verbose_name_plural': 'Url Logs'},
        ),
    ]
