# Generated by Django 3.2.3 on 2021-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0009_alter_urlstat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='longUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urls',
            name='shortUrl',
            field=models.URLField(),
        ),
    ]
