# Generated by Django 3.2.3 on 2021-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0011_alter_urls_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='shortUrl',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
