# Generated by Django 3.2.3 on 2021-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0014_alter_urls_longurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstat',
            name='redirectCount',
        ),
    ]
