# Generated by Django 3.2.3 on 2021-05-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0015_remove_urlstat_redirectcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='shortCode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='shortUrl',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
